---
title: "Lab 4 - Cloud Data, Stat 215A, Fall 2019"
author: 
- "Aya Amanmyradova"
- "Spencer Wilson"
- "Ziyang Zhou"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
   - \usepackage{float}
output: 
  pdf_document:
    number_sections: true
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}

# load in useful packages
library(tidyverse)
library(ggpubr)

# set default knitr chunks
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 6,  # set default width of figures
  fig.height = 4,  # set default height of figures
  fig.align = "center",  # align figure in center
  fig.pos = "H",  # plot figure at the exact location of the code chunk
  cache = FALSE)  # don't cache results

```

```{r load}
# Get the data for three images
path <- "data"
image1 <- read.table(paste0('data/', 'image1.txt'), header = F)
image2 <- read.table(paste0('data/', 'image2.txt'), header = F)
image3 <- read.table(paste0('data/', 'image3.txt'), header = F)

# Add informative column names.
collabs <- c('y','x','label','NDAI','SD','CORR','DF','CF','BF','AF','AN')
names(image1) <- collabs
names(image2) <- collabs
names(image3) <- collabs

# combine images into one dataframe
images <- rbind(image1, image2, image3)
```

# Introduction




# Exploratory Data Analysis

## The Data

## The Variables


```{r labels,  fig.cap = "Expert lables for the presence or absence of clouds, according to a map."}

# Plot the expert pixel-level classification of image 1
p1 <- ggplot(image1) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#9ecae1", "#deebf7"), 
                     labels = c("Ice", "Unknown", "Clouds"))

# Plot the expert pixel-level classification of image 2
p2 <- ggplot(image2) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#9ecae1", "#deebf7"), 
                     labels = c("Ice", "Unknown", "Clouds"))

# Plot the expert pixel-level classification of image 3
p3 <- ggplot(image3) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#9ecae1", "#deebf7"), 
                     labels = c("Ice", "Unknown", "Clouds"))

ggarrange(p1, p2, p3, ncol = 2, nrow = 1, common.legend = TRUE) 
```
```{r corr, results='hide'}

# Correlation matrix of radiances for cloud pixels
corr_cloud <- images %>% 
  filter(label == 1) %>% 
  dplyr::select(DF, CF, BF, AF, AN) %>% 
  cor()
print(corr_cloud)

# Correlation matrix of radiances for non-cloud pixels
corr_ice <- images %>% 
  filter(label == -1) %>% 
  dplyr::select(DF, CF, BF, AF, AN) %>% 
  cor()
print(corr_ice)

# Correlation matrix of NDAI, SD, CORR for cloud pixels
corr2_cloud <- images %>% 
  filter(label == 1) %>% 
  dplyr::select(NDAI, SD, CORR) %>% 
  cor()
print(corr2_cloud)

# Correlation matrix of radiances for non-cloud pixels
corr2_ice <- images %>% 
  filter(label == -1) %>% 
  dplyr::select(NDAI, SD, CORR) %>% 
  cor()
print(corr2_ice)
```
```{r scatter, fig.cap = "Scatterplot of radiances."}

# give labels names
images$lbl <- "Cloud"
images$lbl[images$label == -1] <- "Ice"
images$lbl[images$label == 0] <- "Unknown"

# Convert labels from numeric to factor
images$label <- as.factor(images$label)

# Scatterplots of radiances
p1 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = DF, y = CF, colour = lbl), size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

p2 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = CF, y = BF, colour = lbl), size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

p3 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = BF, y = AF, colour = lbl), size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

p4 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = AF, y = AN, colour = lbl), size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

ggarrange(p1, p2, p3, p4, ncol = 1, nrow = 4) 
```
```{r scatter2, fig.cap = "Scatterplot of NDAI, CORR, and SD."}

# Scatterplots of NDAI, CORR, SD
p1 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = NDAI, y = CORR, colour = lbl), 
             size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

p2 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = NDAI, y = SD, colour = lbl), 
             size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

p3 <- images %>% 
  filter(label != 0) %>% 
  ggplot() + 
  geom_point(aes(x = CORR, y = SD, colour = lbl), 
             size = 0.75, alpha = 0.2) +
  facet_wrap( ~ lbl, ncol=2) + theme(legend.position="none")

ggarrange(p1, p2, p3, ncol = 1, nrow = 3) 
```

#  Modeling

## Feature Selection


```{r feauturs}

# this is a plceholder, should be replaced with random forest
library(leaps)
subsets <- regsubsets(label ~ SD + NDAI + CORR + DF + CF + BF + AF + AN, data = images, nvmax = 3)
summary(subsets)

```

```{r boxplots, fig.cap="Boxplots of best predictors."}

# Boxplots for ice and cloud
#NDAI
p1 <- images %>% 
  filter(label != 0) %>% 
  ggplot(aes(x = lbl, y = NDAI)) + 
  geom_boxplot() + xlab("Label")

#SD
p2 <- images %>% 
  filter(label != 0) %>% 
  ggplot(aes(x = lbl, y = SD)) + 
  geom_boxplot() + xlab("Label")

#CORR
p3 <- images %>% 
  filter(label != 0) %>% 
  ggplot(aes(x = lbl, y = CORR)) + 
  geom_boxplot() + xlab("Label")

ggarrange(p1, p2, p3, ncol = 3, nrow = 1)
```

## Description and Assumptions of Classifiers

## Assessment of fit of Classifiers

## The Best Classifier

## Post-hoc EDA

# Conclusion
