---
title: "lab4-Ziyang"
author: "Ziyang Zhou"
date: "11/18/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
# setwd("~/Desktop/stat-215-a/lab4/")
```

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}

# load in useful packages
library(tidyverse)
library(ggpubr)
library(mlbench)
library(caret)
library(randomForest)
library("gridExtra")
library("grid")
library("corrplot")

# set default knitr chunks
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 6,  # set default width of figures
  fig.height = 4,  # set default height of figures
  fig.align = "center",  # align figure in center
  fig.pos = "H",  # plot figure at the exact location of the code chunk
  cache = FALSE)  # don't cache results

```

```{r}
# Get the data for three images
path <- "data"
image1 <- read.table(paste0('data/', 'image1.txt'), header = F)
image2 <- read.table(paste0('data/', 'image2.txt'), header = F)
image3 <- read.table(paste0('data/', 'image3.txt'), header = F)
image <- c(rep("img1", nrow(image1)),
           rep("img2", nrow(image2)),
           rep("img3", nrow(image3)))
  
# Add informative column names.
collabs <- c('y','x','label','NDAI','SD','CORR','DF','CF','BF','AF','AN')
names(image1) <- collabs
names(image2) <- collabs
names(image3) <- collabs

# combine images into one dataframe
images <- rbind(image1, image2, image3)
images$image <- image
```

# Heuristics EDA
```{r}
## summarizing data
percentage_dat <- images %>%
  group_by(image, label) %>%
  summarise (n = n()) %>%
  mutate(freq = n / sum(n))
  
g1 <- percentage_dat %>%
  filter(image == "img1") %>%
  ggplot(aes(x = label, y = freq)) +
  geom_bar(stat="identity", color="black", fill="lightskyblue3")+
  ylab("Proportion")+
  ylim(0,0.6)

g2 <- percentage_dat %>%
  filter(image == "img2") %>%
  ggplot(aes(x = label, y = freq)) +
  geom_bar(stat="identity", color="black", fill="lightskyblue3")+
  ylab("Proportion")+
  ylim(0,0.6) 
  
g3 <- percentage_dat %>%
  filter(image == "img3") %>%
  ggplot(aes(x = label, y = freq)) +
  geom_bar(stat="identity", color="black", fill="lightskyblue3")+
  ylab("Proportion")+
  ylim(0,0.6) 

grid.arrange(g1, g2, g3, ncol = 3,
             top = textGrob("Proportion of label in each image",
                            gp = gpar(fontsize = 16))) 

## 1 different pattern of cloudiness
## 2 histograms are different across images
## 3 iid assumptions ?
```

```{r}
## correlation plot
corrplot.mixed(cor(images[,c(-3, -12, -13)]))

## discussions
## 1 high positive correlation between five angular features, which
## is consistent with the linear plot (keep one?)
## 2 low positive correlation for NDAI, CORR, and SD.

## distribution plot - density
images$logSD <- log(images$SD + 1)
features <- c('NDAI','logSD','CORR','DF','CF','BF','AF','AN')
images %>%
  filter(label != 0) %>%
  gather(features, 
         key = "Variable", value = "Value") %>%
  ggplot() + 
  geom_density(aes(x = Value, group = label,
                   color = label, fill = label), 
             color = "black", alpha = .7) +
  facet_wrap(Variable ~., 
             scales = "free",
             nrow = 2) +
  theme_bw(base_size = 10) +
  theme(
    plot.title = element_text(size = rel(1.2)),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold")
  ) + 
  labs(x = "") +
  ggtitle("Overlaying Distribution of Labels among Features")

## discussions
## 1 similar label distribution among CF, BF, AF, AN and DF
## 2 quite divergent label distribution among CORR, SD, and NDAI
## 3 NDAI could be good feature in terms of binary classification for 
## labels -1 and 1

## distribution plot - boxplot
images %>%
  filter(label != 0) %>%
  gather(features,
         key = "Variable", value = "Value") %>%
  ggplot() + 
  geom_boxplot(aes(x = label, 
                   y = Value,
                   color= label)) + 
  facet_wrap(Variable ~., 
             scales = "free",
             nrow = 2) +
  theme_bw(base_size = 10) +
  theme(
    plot.title = element_text(size = rel(1.2)),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold")
  ) + 
  labs(x = "") +
  ggtitle("Boxplot Distribution of Labels among Features")

## discussions
## more variation -> better feature
```


# Heuristics Data Splitting

## trivial partition

```{r}
trivial_splits <- function(data){
  res <- list()
  indx <- sample(nrow(data), size = nrow(data)*0.8)
  res$train <- data[indx, ]
  res$test <- data[-indx, ]
  return(res)
}
```


## partition by labels (outcome splits)

```{r}
label_splits <- function(data){
  res <- list()
  indx <- createDataPartition(data$label, p = .8, 
                                  list = FALSE, 
                                  times = 1)
  res$train <- data[indx, ]
  res$test <-  data[-indx, ]
  return(res)
}
```

## partition by blocks (image block splits)

```{r}
block_splits <- function(nrow, ncol, img){
  res <- list()
  train_data <- data.frame()
  val_data <- data.frame()
  test_data <- data.frame()
  min_y_cor <- min(img$y)
  min_x_cor <- min(img$x)
  max_y_cor <- max(img$y)
  max_x_cor <- max(img$x)
  row_grid <- seq(min_y_cor, 
                    max_y_cor + 1,
                    (max_y_cor + 1 - min_y_cor)/(nrow - 1))
  col_grid <- seq(min_x_cor,
                    max_x_cor + 1,
                    (max_x_cor + 1 - min_x_cor)/(ncol - 1))
  
  for (i in 1:length(row_grid) ){
    for (j in 1:length(col_grid) ){
      img_chunk <- img[img$y >= row_grid[i] & 
                         img$y < row_grid[i + 1] & 
                         img$x >= col_grid[j] & 
                         img$x < col_grid[j + 1], ]
      indx_test_val <- sample(nrow(img_chunk), 
                                 size = floor(nrow(img_chunk) * 0.4))
      indx_val <- sample(indx_test_val,
                         size = floor(length(indx_test_val)/2))
      indx_test <- indx_test_val[!indx_test_val %in% indx_val]
      test_set <- img_chunk[indx_test, ]
      val_set <- img_chunk[indx_val, ]
      train_set <- img_chunk[-indx_test_val, ]
      train_data <- rbind(train_data, train_set)
      test_data <- rbind(test_data, test_set)
      val_data <- rbind(val_data, val_set)
    }
  }
  
  res$training <- train_data
  res$validation <- val_data
  res$test <- test_data
  res$row_grid <- row_grid
  res$col_grid <- col_grid
  return(res)
}

image1 <- image1 %>% filter(label != 0)
image2 <- image2 %>% filter(label != 0)
image3 <- image3 %>% filter(label != 0)
naive_split_result_1 <- trivial_splits(image1)
label_split_result_1 <- label_splits(image1)
block_split_result_1 <- block_splits(10,10,image1)
naive_split_result_2 <- trivial_splits(image2)
label_split_result_2 <- label_splits(image2)
block_split_result_2 <- block_splits(10,10,image2)
naive_split_result_3 <- trivial_splits(image3)
label_split_result_3 <- label_splits(image3)
block_split_result_3 <- block_splits(10,10,image3)

x_cord1 <- block_split_result_1$col_grid
y_cord1 <- block_split_result_1$row_grid
x_cord2 <- block_split_result_2$col_grid
y_cord2 <- block_split_result_2$row_grid
x_cord3 <- block_split_result_3$col_grid
y_cord3 <- block_split_result_3$row_grid

img1 <- ggplot(image1) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord1, linetype = "dashed") + 
  geom_hline(yintercept = y_cord1, linetype = "dashed") + 
  ggtitle("original image1")

block1 <- block_split_result_1$training %>%
ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord1, linetype = "dashed") + 
  geom_hline(yintercept = y_cord1, linetype = "dashed") +
  ggtitle("image1 blocking splits")

naive1 <- naive_split_result_1$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord1, linetype = "dashed") + 
  geom_hline(yintercept = y_cord1, linetype = "dashed") + 
  ggtitle("image1 trivial splits")


label1 <- label_split_result_1$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord1, linetype = "dashed") + 
  geom_hline(yintercept = y_cord1, linetype = "dashed") +
  ggtitle("image1 label splits")

#grid.arrange(img1, naive1, block1, label1, ncol = 2)

img2 <- ggplot(image2) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord2, linetype = "dashed") + 
  geom_hline(yintercept = y_cord2, linetype = "dashed") + 
  ggtitle("original image2")

block2 <- block_split_result_2$training %>%
ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord2, linetype = "dashed") + 
  geom_hline(yintercept = y_cord2, linetype = "dashed") +
  ggtitle("image2 blocking splits")

naive2 <- naive_split_result_2$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord2, linetype = "dashed") + 
  geom_hline(yintercept = y_cord2, linetype = "dashed") + 
  ggtitle("image2 trivial splits")


label2 <- label_split_result_2$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord2, linetype = "dashed") + 
  geom_hline(yintercept = y_cord2, linetype = "dashed") +
  ggtitle("image2 label splits")

#grid.arrange(img2, naive2, block2, label2, ncol = 2)

img3 <- ggplot(image3) + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord3, linetype = "dashed") + 
  geom_hline(yintercept = y_cord3, linetype = "dashed") + 
  ggtitle("original image3")

block3 <- block_split_result_3$training %>%
ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border= element_blank(),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord3, linetype = "dashed") + 
  geom_hline(yintercept = y_cord3, linetype = "dashed") +
  ggtitle("image3 blocking splits")

naive3 <- naive_split_result_3$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord3, linetype = "dashed") + 
  geom_hline(yintercept = y_cord3, linetype = "dashed") + 
  ggtitle("image3 trivial splits")


label3 <- label_split_result_3$train %>%
  ggplot() + 
  geom_point(aes(x = x, y = y, color = factor(label))) + 
  theme_bw() +
  theme(axis.text = element_text(size = 5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border= element_blank(),
          legend.text = element_text(size =10),
          legend.title = element_text(size = 15))+
  scale_color_manual(name = "Expert label", 
                     values = c("#3182bd", "#deebf7"), 
                     labels = c("Ice", "Clouds")) +
  geom_vline(xintercept = x_cord3, linetype = "dashed") + 
  geom_hline(yintercept = y_cord3, linetype = "dashed") +
  ggtitle("image1 label splits")

#grid.arrange(img3, naive3, block3, label3, ncol = 2)

grid.arrange(img1, naive1, block1, label1,
             img2, naive2, block2, label2,
             img3, naive3, block3, label3, ncol = 4)
```

